<a href="https://colab.research.google.com/github/Monserrate5/tarea/blob/main/Deber01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
array = np.arange(10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
import numpy as np
matrix = np.ones((3, 3), dtype=bool)
print(matrix)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [ ]:
array = np.arange(10)
# Filtrar los números impares
odds = array[array % 2 != 0]
print(odds)

[1 3 5 7 9]


In [ ]:
array = np.arange(10)
# Filtrar los números impares
odds = array[array % 2 != 0] - 1
print(odds)

[0 2 4 6 8]


In [ ]:
array = np.arange(10)
# Convertir la matriz 1D en una matriz 2D con 2 filas
arr_2d = np.reshape(array, (2, -1))
print(arr_2d)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [ ]:
b=np.random.randint(low=4,high=12,size=(2,2))
b

array([[ 9,  7],
       [10,  9]])

In [ ]:
c=np.random.randint(low=4,high=12,size=(2,2))
c

array([[9, 5],
       [9, 5]])

In [ ]:
aux=np.vstack((b,c))
print(aux)

[[ 9  7]
 [10  9]
 [ 9  5]
 [ 9  5]]


In [ ]:
aux=np.hstack((b,c))
print(aux)

[[ 9  7  9  5]
 [10  9  9  5]]


In [ ]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

# Obtener los elementos entre las posiciones 5 y 10
articulo = a[5:10]

print(articulo)

[6, 7, 8, 9, 10]


In [ ]:
def maxx(x,y):
    """Get the maximum of two items"""
    if x >= y:
         return x
    else:
         return y
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
    #maxx(a,b)
tmp=list()
for i in range(len(a)):
   tmp.append(maxx(a[i],b[i]))

print(tmp)

[6, 7, 9, 8, 9, 7, 5]


In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Intercambiar las columnas 1 y 2
arr[:, [1, 2]] = arr[:, [2, 1]]

print(arr)

[[1 3 2]
 [4 6 5]
 [7 9 8]]


In [ ]:
# Crear una matriz 2D de forma 5x3 con números decimales aleatorios entre 0 y 5
matriz = np.random.rand(5, 3) * 5

print(matriz)

[[4.43724763 1.01276308 3.51918382]
 [2.15234178 1.09238586 1.56175839]
 [2.48822574 3.58244102 3.49628722]
 [1.30843848 3.75286216 4.78945107]
 [4.91428005 1.15466138 2.258628  ]]
