<a href="https://colab.research.google.com/github/Monserrate5/tarea/blob/main/tarea1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!python --version

Python 3.10.12


In [6]:
import numpy as np
tarea=np.array([3,33,333])
print(tarea)
print(tarea.shape)

[  3  33 333]
(3,)


In [10]:
b=np.zeros((4,6))
b
print(b.shape)
print(b)
b[3,3]=120
print(b)
print(b[:,[2,3]])
#print(b)

print(b[:,[3,2]])
#print(b)

(4, 6)
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0. 120.   0.   0.]]
[[  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [  0. 120.]]
[[  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [120.   0.]]


In [18]:
c=np.random.randint(low=4,high=12,size=(2,2))
c

array([[ 8, 11],
       [ 4,  4]])

In [20]:
d=np.random.randint(low=1,high=8,size=(2,2))
d

array([[5, 3],
       [3, 6]])

In [19]:
aux=np.vstack((c,d))
print(aux)

[[ 8 11]
 [ 4  4]
 [ 2  7]
 [ 4  7]]


In [21]:
aux=np.hstack((c,d))
print(aux)

[[ 8 11  5  3]
 [ 4  4  3  6]]
