<a href="https://colab.research.google.com/github/Monserrate5/tarea/blob/main/tarea1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!python --version

Python 3.10.12


In [ ]:
import numpy as np
tarea=np.array([3,33,333])
print(tarea)
print(tarea.shape)

[  3  33 333]
(3,)


In [ ]:
b=np.zeros((4,6))
b
print(b.shape)
print(b)
b[3,3]=120
print(b)
print(b[:,[2,3]])
#print(b)

print(b[:,[3,2]])
#print(b)

(4, 6)
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0. 120.   0.   0.]]
[[  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [  0. 120.]]
[[  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [120.   0.]]


In [ ]:
c=np.random.randint(low=4,high=12,size=(2,2))
c

array([[ 8, 11],
       [ 4,  4]])

In [ ]:
d=np.random.randint(low=1,high=8,size=(2,2))
d

array([[5, 3],
       [3, 6]])

In [ ]:
aux=np.vstack((c,d))
print(aux)

[[ 8 11]
 [ 4  4]
 [ 2  7]
 [ 4  7]]


In [ ]:
aux=np.hstack((c,d))
print(aux)

[[ 8 11  5  3]
 [ 4  4  3  6]]


In [ ]:
c=np.random.randint(low=1,high=14,size=(9))
print(c)
print(c.shape)

[13  4 10  8  3  6  6  5  8]
(9,)


In [ ]:
filter=(c<4)
print(c[filter])

[3]


In [ ]:
c[c%2==0]

array([ 4, 10,  8,  6,  6,  8])

In [ ]:
c[c%2!=0] #even or old

array([13,  3,  5])

In [ ]:
c[c%2!=0]=100
print(c) #para reemplazar

[ 0  4 10  8  0  6  6  0  8]


In [ ]:
c=np.random.randint(low=1,high=14,size=(9))
print(c)
print(c.shape)

[ 4  7  1  2  6  6 10 12  6]
(9,)


In [ ]:
c[(c>5) & (c<10)]

array([7, 6, 6, 6])

In [8]:
import numpy as np

def maxx(x,y):
    """Get the maximum of two items"""
    if x >= y:
         return x
    else:
         return y
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
    #maxx(a,b)
tmp=list()
for i in range(len(a)):
   tmp.append(maxx(a[i],b[i]))

print(tmp)

[6, 7, 9, 8, 9, 7, 5]


In [5]:
newFuctionArrays=np.vectorize(maxx)
newFuctionArrays(a,b)

array([6, 7, 9, 8, 9, 7, 5])